### ISSUE TITLE
[PE-D][Tester E] "note 1" removes note for index 1

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-4/tp#179]
![Screenshot 2023-11-03 at 4.19.21 PM.png](https://raw.githubusercontent.com/tohpinren/ped/main/files/83a74593-39af-4cad-a40b-aa3afcab6f0b.png)

Entering "note 1" removes the note from person 1.

Is this the intended effect? It is not in the UG

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: tohpinren/ped#4

**Comment by SimWPEric** [comment]
Same as #195.
