### ISSUE TITLE
[PE-D][Tester E] Able to schedule appointments for past dates

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-4/tp#183]
![Screenshot 2023-11-03 at 4.22.35 PM.png](https://raw.githubusercontent.com/tohpinren/ped/main/files/47366468-9e1c-443b-8c1b-f86cf65a7b74.png)

Should I be allowed to schedule appointments for dates in the past?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: tohpinren/ped#5

**Comment by SimWPEric** [comment]
Same as #222.
