### ISSUE TITLE
[PE-D][Tester C] Tag inputs are not case insensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-4/tp#217]
![image.png](https://raw.githubusercontent.com/matochichap/ped/main/files/c82cbaca-718c-4dc2-9b91-0f665db20a40.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: matochichap/ped#11

**Comment by SimWPEric** [comment]
Can make risk level case insensitive.
