### ISSUE TITLE
[PE-D][Tester C] Title case and lower case names are treated as different names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-4/tp#228]
![image.png](https://raw.githubusercontent.com/matochichap/ped/main/files/8c8b128a-ca1f-473d-a2a5-c6f93840a292.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: matochichap/ped#22

**Comment by SimWPEric** [comment]
Update UG
